-- Add pipeline_run_id to link all job_runs from a single daily_sync.sh execution
ALTER TABLE audit.job_runs
ADD COLUMN IF NOT EXISTS pipeline_run_id UUID;

COMMENT ON COLUMN audit.job_runs.pipeline_run_id IS
'UUID generated by daily_sync.sh at pipeline start.
Links all job_runs from a single pipeline execution.
NULL for jobs run outside daily_sync.sh (manual, ad-hoc).';

-- Fix hung pipelines: mark as failed if stuck in running for more than 4 hours
UPDATE audit.job_runs
SET status = 'failed',
    error_message = 'Marked failed by migration: status stuck in running > 4h',
    end_time = start_time + INTERVAL 4 HOURS
WHERE status = 'running'
AND start_time < NOW() - INTERVAL 4 HOURS;
