CREATE VIEW [gold].[vw_Dim_Date]
AS
SELECT [SK_Date]
      ,[Dato]
      ,[Aar]
      ,[Kvartal]
      ,[Maaned]
      ,[Uge]
      ,[Dag_Nr_I_Uge]
      ,[Dag_Nr_I_Aar]
      ,[Dag_Nr_I_Maaned]
      ,[Maaned_Navn]
      ,[Dag_Navn]
      ,[Skudaar]
      ,[Uge_Nr_I_Maaned]
      ,[Maaned_Nr_I_Kvartal]
      ,[Aar_Maaned_Nr]
  FROM [silver].[Dim_Date]

UNION

SELECT 
 0   AS [SK_Date]
,NULL AS [Dato]
,NULL AS [Aar]
,NULL AS [Kvartal]
,NULL AS [Maaned]
,NULL AS [Uge]
,NULL AS [Dag_Nr_I_Uge]
,NULL AS [Dag_Nr_I_Maaned]
,NULL AS [Dag_Nr_I_Aar]
,NULL AS [Maaned_Navn]
,NULL AS [Dag_Navn]
,NULL AS [Skudaar]
,NULL AS [Uge_Nr_I_Maaned]
,NULL AS [Maaned_Nr_I_Kvartal]
,NULL AS [Aar_Maaned_Nr]