CREATE VIEW [gold].[vw_Fact_DailySleep]
AS
SELECT 
	   [SK_Date_BedtimeStart]
      ,[SK_Time_BedtimeStart]
      ,[SK_Date_BedtimeEnd]
      ,[SK_Time_BedtimeEnd]
      ,CAST(SUBSTRING(REPLACE(REPLACE([Date],'"',''),'-',''),1,8)AS INT) AS [SK_Date]
      ,[AverageBreath (min)]
      ,[AverageHeartRate]
      ,[LowestHeartRate]
      ,[AverageHeartRateVariability]
      ,[DeepSleepDuration (sec)]
      ,[LightSleepDuration (sec)]
      ,[RemSleepDuration (sec)]
      ,[RestlessPeriods (sec)]
      ,[TemperatureDeviation]
      ,[TemperatureTrendDeviation]
      ,[SleepEfficiency in %]
      ,[SleepLatency (sec)]
      ,[SleepPeriods]
      ,[SleepScore]
      ,[SleepSegmentState]
      ,[SleepMidpoint (sec)]
      ,[TimeInBed (sec)]
      ,[TotalSleepDuration (sec)]
      ,[AwakeTime (sec)]
      ,[SleepType]
  FROM [silver].[DailySleep]