CREATE VIEW [gold].[vw_Fact_DailyMeal]
AS
SELECT 
       [SK_Date]
      ,[SK_MealType]
      ,[SK_FoodItem]
      ,[Amount in grams]
      ,[Calories]
      ,[Carbs]
      ,[Carbs fiber]
      ,[Carbs sugar]
      ,[Fat]
      ,[Fat saturated]
      ,[Fat unsaturated]
      ,[Cholesterol]
      ,[Protein]
      ,[Potassium]
      ,[Sodium]
  FROM [silver].[DailyMeal]