CREATE VIEW [gold].[vw_Dim_Time]
AS
SELECT [SK_Time]
      ,[Ekey_Time]
      ,[TimeCode]
      ,[Hour12Code]
      ,[Hour12Key]
      ,[MinuteCode]
      ,[MinuteKey]
      ,[AMPMCode]
      ,[Hour24Code]
      ,[Hour24Key]
      ,[Minute15Code]
      ,[Minute15Key]
  FROM [silver].[Dim_Time]
  UNION

  SELECT 
   0 AS [SK_Time]
  ,NULL [Ekey_Time]
  ,NULL [TimeCode]
  ,NULL [Hour12Code]
  ,NULL [Hour12Key]
  ,NULL [MinuteCode]
  ,NULL [MinuteKey]
  ,NULL [AMPMCode]
  ,NULL [Hour24Code]
  ,NULL [Hour24Key]
  ,NULL [Minute15Code]
  ,NULL [Minute15Key]